module.exports = {
  CONST_SHOUT_CASE: 'SHOUT_CASE variables expected to be const.',
  EXPECTED_CAMEL_CASE: 'Expected camelCase name.',
  EXPECTED_PASCAL_CASE: 'Expected a PascalCase name following ‘new’.',
  NO_VAR: 'Expected let or const instead of var.',
  DETECTED_NESTED_FUNC_DECLARATION: 'Detected nested function declaration.',
  DETECTED_COMMENTED_OUT_CODE: 'Detected potentially commented-out code.',
  DETECTED_ESLINT_DISABLE: 'Detected disabled ESLint rule(s).',
  DETECTED_DEPRECATED_HTML_ELEMENT: 'Detected deprecated HTML Element.',
  DETECTED_PASCAL_CASE: 'Detected PascalCase function name.',
  DETECTED_NOISE_WORD_AFFIX: 'Detected noise word as name prefix or suffix.',
  DETECTED_SINGLE_LETTER_NAME: 'Detected single letter name.',
  DETECTED_NAME_X: 'Detected ‘x the Unknown’ as a name.',
  DETECTED_NAME_L: 'Detected ‘l’ as a name: easily confused with the number ‘1’',
  DETECTED_NUMERIC_SUFFIX: 'Detected numeric suffix in identifier.',
  DETECTED_ITERATIVE_FOR_LOOP: 'Detected iterative for-loop: suggest array method.',
};
