module.exports = {
  CONST_SHOUT_CASE: 'SHOUT_CASE variables expected to be const.',
  DETECTED_CLASSIC_FOR_LOOP: 'Classic for-loop: suggest array method.',
  DETECTED_COMMENTED_OUT_CODE: 'Potentially commented-out code.',
  DETECTED_DEPRECATED_HTML_ELEMENT: 'Deprecated HTML Element.',
  DETECTED_ESLINT_DISABLE: 'Disabled ESLint rule(s).',
  DETECTED_NAME_L: 'Found ‘l’ as a name: easily confused with the number ‘1’',
  DETECTED_NAME_X: 'Found ‘x’ as a name: unknown?',
  DETECTED_NESTED_FUNC_DECLARATION: 'Nested function declaration.',
  DETECTED_NOISE_WORD_AFFIX: 'Noise word as name prefix or suffix.',
  DETECTED_NUMERIC_SUFFIX: 'Numeric suffix in identifier.',
  DETECTED_PASCAL_CASE: 'PascalCase function name.',
  DETECTED_SINGLE_LETTER_NAME: 'Single letter name.',
  EXPECTED_CAMEL_CASE: 'Expected camelCase name.',
  EXPECTED_PASCAL_CASE: 'Expected a PascalCase name following ‘new’.',
  NO_VAR: 'Expected let or const instead of var.',

  ARRAY_PATTERN: 'ArrayPattern',
  ARROW_EXPRESSION: 'ArrowExpression',
  ARROW_FUNCTION_EXPRESSION: 'ArrowFunctionExpression',
  ASSIGNMENT_PATTERN: 'AssignmentPattern',
  FOR_STATEMENT: 'ForStatement',
  FUNCTION_EXPRESSION: 'FunctionExpression',
  IDENTIFIER: 'Identifier',
  JSX_IDENTIFIER: 'JSXIdentifier',
  LITERAL: 'Literal',
  MEMBER_EXPRESSION: 'MemberExpression',
  OBJECT_PATTERN: 'ObjectPattern',
  REST_ELEMENT: 'RestElement',
  VARIABLE_DECLARATION: 'VariableDeclaration',
  VARIABLE_DECLARATOR: 'VariableDeclarator',
};
