module.exports = {
  CONST_SHOUT_CASE: 'SHOUT_CASE variables expected to be const.',
  EXPECTED_CAMEL_CASE: 'Expected camelCase name.',
  EXPECTED_PASCAL_CASE: 'Expected a PascalCase name following ‘new’.',
  NO_VAR: 'Expected let or const instead of var.',
  DETECTED_NESTED_FUNC_DECLARATION: 'Nested function declaration.',
  DETECTED_COMMENTED_OUT_CODE: 'Potentially commented-out code.',
  DETECTED_ESLINT_DISABLE: 'Disabled ESLint rule(s).',
  DETECTED_DEPRECATED_HTML_ELEMENT: 'Deprecated HTML Element.',
  DETECTED_PASCAL_CASE: 'PascalCase function name.',
  DETECTED_NOISE_WORD_AFFIX: 'Noise word as name prefix or suffix.',
  DETECTED_SINGLE_LETTER_NAME: 'Single letter name.',
  DETECTED_NAME_X: 'Found ‘x the Unknown’ as a name.',
  DETECTED_NAME_L: 'Found ‘l’ as a name: easily confused with the number ‘1’',
  DETECTED_NUMERIC_SUFFIX: 'Numeric suffix in identifier.',
  DETECTED_CLASSIC_FOR_LOOP: 'Classic for-loop: suggest array method.',
};
